# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-09 14:23
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type_name', models.CharField(max_length=200)),
                ('_growth_days', models.IntegerField(validators=django.core.validators.MinValueValidator(0))),
                ('_create_record_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_start_plant_timestamp', models.DateTimeField()),
                ('_end_plant_timestamp', models.DateTimeField()),
                ('_create_record_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('_is_harvested', models.BooleanField()),
                ('_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
